[{"id":583396188,"node_id":"R_kgDOIsXrXA","name":"CVE-2022-35983","full_name":"Live-Hack-CVE/CVE-2022-35983","private":false,"owner":{"login":"Live-Hack-CVE","id":121191732,"node_id":"O_kgDOBzk9NA","avatar_url":"https://avatars.githubusercontent.com/u/121191732?v=4","url":"https://api.github.com/users/Live-Hack-CVE","html_url":"https://github.com/Live-Hack-CVE","type":"Organization","site_admin":false},"html_url":"https://github.com/Live-Hack-CVE/CVE-2022-35983","description":"TensorFlow is an open source platform for machine learning. If `Save` or `SaveSlices` is run over tensors of an unsupported `dtype`, it results in a `CHECK` fail that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit 5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4. The fix will be i CVE project by @Sn0wAlice","fork":false,"url":"https://api.github.com/repos/Live-Hack-CVE/CVE-2022-35983","created_at":"2022-12-29T16:48:30Z","updated_at":"2022-12-29T16:48:30Z","pushed_at":"2022-12-29T16:48:32Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1}]