[{"id":583396372,"node_id":"R_kgDOIsXsFA","name":"CVE-2022-35994","full_name":"Live-Hack-CVE/CVE-2022-35994","private":false,"owner":{"login":"Live-Hack-CVE","id":121191732,"node_id":"O_kgDOBzk9NA","avatar_url":"https://avatars.githubusercontent.com/u/121191732?v=4","url":"https://api.github.com/users/Live-Hack-CVE","html_url":"https://github.com/Live-Hack-CVE","type":"Organization","site_admin":false},"html_url":"https://github.com/Live-Hack-CVE/CVE-2022-35994","description":"TensorFlow is an open source platform for machine learning. When `CollectiveGather` receives an scalar input `input`, it gives a `CHECK` fails that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit c1f491817dec39a26be3c574e86a88c30f3c4770. The fix will be included in TensorFl CVE project by @Sn0wAlice","fork":false,"url":"https://api.github.com/repos/Live-Hack-CVE/CVE-2022-35994","created_at":"2022-12-29T16:49:07Z","updated_at":"2022-12-29T16:49:07Z","pushed_at":"2022-12-29T16:49:10Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1}]